### PR TITLE
chore(py2): compatibility layer to Python2.7. Fixes #46

### LINKED ISSUE #46: Bring back Python 2 compatibility
thank you for working on this so much recently, @Ryuno-Ki! it's great to have a maintainer again.

i noticed that one of your early changes was to remove Python 2 compatibility, in particular by adding httplink as dependency, which is Python 3 only.

sadly i have to keep granary and Bridgy Python 2 compatible for the foreseeable future, at least for a year or two more, due to both existing users and App Engine standard APIs still requiring it. this means i can't use your new package as is, so i'd have to continue using my fork instead.

sorry if this is a surprise. let me know if i can answer any questions!

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

### CODE REVIEW

**Comment by snarfed** [comment]
this passes all of bridgy's tests. thanks for doing it!

**Comment by Ryuno-Ki** [comment]
Thanks for the feedback.
Let's see, what @joernheissler thinks about https://github.com/joernheissler/httplink/issues/1 :-)

**Comment by Ryuno-Ki** [comment]
@snarfed Except some coverage hits, the code is fine from my side. Shall I merge or do you want to give it another pass?
(Replaced vendor file with fork on GitHub).

**Comment by snarfed** [comment]
merging is your call, as maintainer! bridgy's tests all still pass with the new commits, so i'm fine with it if you want.

**Pull request merged**
